"""The two analysis scripts the source comments cite.

src/config.py said NEVER_AUTO_RESPOND was "verified in
scripts/check_policy_classes.py" and src/text.py said EXPANSIONS candidates were
regenerated by scripts/build_expansions.py. Neither file existed, so both
comments were pointing at nothing. They exist now, and a script nobody runs
rots, so the invariant each one checks is asserted here as well.
"""

from __future__ import annotations

import json

from scripts import build_expansions, check_policy_classes
from src.config import NEVER_AUTO_RESPOND


# FR-13. The four classes are a policy decision, but the claim in config.py is
# that they cover everything the data flags, and that is checkable.
def test_every_intent_the_data_flags_is_in_never_auto_respond(repo_root):
    for name in ("development_tickets.json", "validation_tickets.json"):
        result = check_policy_classes.audit(str(repo_root / "data" / name))

        assert result["intents_flagged_but_not_in_config"] == [], name
        assert result["ok"] is True, name


def test_the_development_set_flags_the_four_classes_the_prd_names(repo_root):
    result = check_policy_classes.audit(str(repo_root / "data" / "development_tickets.json"))

    assert result["flagged_tickets"] == 87
    assert result["flagged_by_intent"] == {
        "compliance_request": 26,
        "feature_request": 20,
        "security_incident": 26,
        "unclear_request": 15,
    }
    assert set(result["flagged_by_intent"]) <= NEVER_AUTO_RESPOND


def test_the_policy_check_fails_loudly_when_a_flagged_intent_is_not_covered(tmp_path):
    # The case it exists to catch: a later dataset flags an intent config does
    # not forbid, and nothing but the confidence threshold stands in the way.
    tickets = [
        {
            "ticket_id": "POL-1",
            "channel": "email",
            "subject": "",
            "body": "a ticket long enough to be ingested without complaint",
            "labels": {"intent": "billing_query", "must_not_auto_respond": True},
        }
    ]
    path = tmp_path / "tickets.json"
    path.write_text(json.dumps(tickets), encoding="utf-8")

    result = check_policy_classes.audit(str(path))

    assert result["ok"] is False
    assert result["intents_flagged_but_not_in_config"] == ["billing_query"]
    assert check_policy_classes.main(["--input", str(path)]) == 1


def test_the_policy_check_exits_zero_on_the_shipped_data(repo_root):
    assert check_policy_classes.main([]) == 0


def test_the_expansion_generator_proposes_documentation_vocabulary(tmp_path):
    # It regenerates candidates; it does not edit src/text.py. The assertion is
    # that it produces suggestions made of words the corpus actually uses, and
    # that it marks the ones already curated rather than proposing them again.
    output = tmp_path / "candidates.json"

    assert build_expansions.main(["--output", str(output), "--limit", "5"]) == 0

    summary = json.loads(output.read_text(encoding="utf-8"))
    assert summary["tickets_considered"] > 0
    assert summary["rows"]

    from src.retrieve import Retriever
    from src.text import EXPANSIONS

    corpus_words = set()
    for doc in Retriever().documents.values():
        corpus_words |= build_expansions.article_tokens(doc)

    for row in summary["rows"]:
        assert row["tickets"] >= build_expansions.MIN_TICKETS
        assert len(row["suggested_terms"]) <= build_expansions.TOP_TERMS
        assert set(row["suggested_terms"]) <= corpus_words
        assert row["already_in_expansions"] == (row["customer_word"] in EXPANSIONS)


def test_the_expansion_generator_can_be_narrowed_to_the_tickets_retrieval_misses(tmp_path):
    output = tmp_path / "misses.json"

    assert build_expansions.main(["--output", str(output), "--misses-only", "--limit", "5"]) == 0

    summary = json.loads(output.read_text(encoding="utf-8"))
    assert summary["misses_only"] is True
    # Retrieval recall is 96.4%, so this list is short by construction. If it
    # ever covered most of the set, something else has broken.
    assert 0 < summary["tickets_considered"] < 60
